<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fp_misereor"
 *
 * Auto generated by Extension Builder 2018-07-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Tetris Template',
    'description' => 'Das Template für Tetris.',
    'category' => 'templates',
    'author' => 'Yannik Börgener',
    'author_email' => 'kontakt@boergener.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.1.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
